[package]
name = "jpeg_processor"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["jpeg_compressor", "jpeg_converter"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true

[dependencies]
